config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "pics#index"

  resources :pics do
    resources :comments, only: [:create]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :pic
  belongs_to :user
end

app/models/pic.rb
class Pic < ApplicationRecord
  validates :message, presence: true
  validates :picture, presence: true

  belongs_to :user
  has_many :comments

  mount_uploader :picture, PictureUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pics
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def render_not_found(status=:not_found)
    render plain: "#{status.to_s.titleize} :(", status: status
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, only: [:create]

  def create
    @pic = Pic.find_by_id(params[:pic_id])
    return render_not_found if @pic.blank?
    @pic.comments.create(comment_params.merge(user: current_user))
    redirect_to root_path
  end

  private

  def comment_params
    params.require(:comment).permit(:message)
  end

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]

  def show
    @pic = Pic.find_by_id(params[:id])
    return render_not_found if @pic.blank?
  end

  def index
    @pics = Pic.order(id: :desc)
  end

  def new
    @pic = Pic.new
  end

  def create
    @pic = current_user.pics.create(pic_params)
    if @pic.valid?
      redirect_to root_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @pic = Pic.find_by_id(params[:id])
    return render_not_found if @pic.blank?
    return render_not_found(:forbidden) if @pic.user != current_user
  end

  def update
    @pic = Pic.find_by_id(params[:id])
    return render_not_found if @pic.blank?
    return render_not_found(:forbidden) if @pic.user != current_user

    @pic.update_attributes(pic_params)
    if @pic.valid?
      redirect_to root_path
    else
      return render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @pic = Pic.find_by_id(params[:id])
    return render_not_found if @pic.blank?
    return render_not_found(:forbidden) if @pic.user != current_user
    @pic.destroy
    redirect_to root_path
  end

  private

  def pic_params
    params.require(:pic).permit(:message, :picture)
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Plant Pics</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css?family=Grand+Hotel|Josefin+Sans" rel="stylesheet">
  </head>

  <body>
    <div class="top-nav d-flex">
      <div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
        <div class="brand float-left">
          <%= link_to 'Plant Pics', root_path %>
        </div>
        <div class="add float-right">
          <% if current_user %>
            Welcome, <%= current_user.name %>.
            <%= link_to 'New Post', new_pic_path %>
            <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to 'Sign In', new_user_session_path %>
            <%= link_to 'Sign Up', new_user_registration_path %>
          <% end %>
        </div>
      </div>
      <br class="clear-fix" />
    </div>

    <% if notice.present? %>
      <p class="alert alert-info"><%= notice %></p>
    <% end %>
    <% if alert.present? %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/pics/edit.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">

  <h1>Edit Plant Pic</h1>

  <%= simple_form_for @pic do |f| %>
    <%= f.input :message %>
    <%= f.input :picture %>
    <%= f.submit "Update", class: 'wide-btn' %>
  <% end %>

</div>

app/views/pics/index.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3">
  <% @pics.each do |pic| %>
    <div class="card">
      <div class="handle">
        <%= pic.user.name %>
        <span class="float-right">&nbsp;&nbsp;&nbsp;<%= pic.created_at.strftime("%m/%d/%Y") %></span>
        <span class="pic-actions float-right">
          <% if current_user && current_user == pic.user %>
            <%= link_to 'Edit Post', edit_pic_path(pic) %>&nbsp;&nbsp;
            <%= link_to 'Delete Post', pic_path(pic), method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </span>
      </div>
      <%= image_tag pic.picture, class: 'img-fluid' %>
      <p>
        <%= pic.message %>
      </p>
      <br class="clear-fix" />
      <div class="comments">
        <h3>Comments</h3>
        <% pic.comments.each do |comment| %>
          <div class="comment">
            &ldquo;<%= comment.message %>&rdquo;
            <span class="comment-handle float-right">
              - <%= comment.user.name %>
            </span>
          </div>
          <br class="clear-fix" />
        <% end %>
        <%= simple_form_for Comment.new, url: pic_comments_path(pic) do |f| %>
          <%= f.input :message, label: false, placeholder: '(add a comment)' %>
          <%= f.submit 'Comment', class: 'wide-btn' %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>

app/views/pics/new.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card form">

  <h1>New Plant Pic</h1>

  <%= simple_form_for @pic do |f| %>
    <%= f.input :message %>
    <%= f.input :picture %>
    <%= f.submit "Post", class: 'wide-btn' %>
  <% end %>

</div>

app/views/pics/show.html.erb
<div class="col-10 offset-1 col-sm-8 offset-sm-2 col-md-6 offset-md-3 card">

<div class="handle">
    <%= @pic.user.name %>
    <span class="@pic-actions float-right">
      <% if current_user && current_user == @pic.user %>
        <%= link_to 'Edit Post', edit_pic_path(@pic) %>&nbsp;&nbsp;
        <%= link_to 'Delete Post', pic_path(@pic), method: :delete, data: {confirm: 'Are you sure?'} %>
      <% end %>
    </span>
  </div>
  <%= image_tag @pic.picture, class: 'img-fluid' %>
  <p>
    <%= @pic.message %>
  </p>

</div>